# Generated by Django 2.0.3 on 2018-04-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='FeedbackList',
        ),
    ]
