# Generated by Django 2.0.3 on 2018-04-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180412_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
